export enum ErrorCode {
      USER_NOT_FOUND = "USER_NOT_FOUND",
      INVALID_REQUEST = "INVALID_REQUEST",
      DATABASE_ERROR = "DATABASE_ERROR",
      UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS",
      INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
      VALIDATION_FAILED = "VALIDATION_FAILED",
      RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
      EMAIL_EXIST = "EAMIL_EXIST",
      PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
      OUT_OF_STOCK="OUT_OF_STOCK"
    }